# Generated by Django 2.2.1 on 2019-05-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('A', 'Administrador'), ('U', 'Usuario')], default='U', max_length=1),
        ),
    ]
