# Generated by Django 2.2.1 on 2019-05-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0002_auto_20190512_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre_usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=50)),
                ('url_contenido', models.URLField()),
                ('descripcion', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('url_portada', models.URLField()),
                ('score', models.CharField(max_length=1)),
                ('actores', models.ManyToManyField(to='streamflix.Actores')),
            ],
        ),
    ]
