# Generated by Django 2.2.1 on 2019-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0003_auto_20190513_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('A', 'Administrador'), ('U', 'Usuario')], default='U', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
