# Generated by Django 2.2.1 on 2019-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0004_auto_20190519_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=1234, max_length=32),
        ),
    ]
