# Generated by Django 2.2.1 on 2019-05-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0006_auto_20190519_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-id']},
        ),
    ]
