# Generated by Django 2.2.1 on 2019-05-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0009_auto_20190520_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actores',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-id']},
        ),
    ]
