# Generated by Django 2.2.1 on 2019-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0010_auto_20190520_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url_portada',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
