# Generated by Django 2.2.1 on 2019-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0011_auto_20190521_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nombre_actor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
