# Generated by Django 2.2.1 on 2019-05-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0012_auto_20190522_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='score',
            new_name='Metascore',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='descripcion',
            new_name='Plot',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='url_portada',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='Year',
        ),
    ]
