# Generated by Django 2.2.1 on 2019-05-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0017_movie_actores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actores',
            new_name='Actors',
        ),
    ]
