# Generated by Django 2.2.1 on 2019-05-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0018_auto_20190525_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
