# Generated by Django 2.2.1 on 2019-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0020_auto_20190529_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.ImageField(upload_to=''),
        ),
    ]
